<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net6.0-windows7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<XamlDebuggingInformation>True</XamlDebuggingInformation>
		<PlatformTarget>x64</PlatformTarget>
		<BaseOutputPath>../</BaseOutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Configurations>DebugEditor;ReleaseEditor</Configurations>
		<Platforms>x64</Platforms>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='DebugEditor|x64'">
	  <Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='ReleaseEditor|x64'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="Resources\ContentBrowser\TileView.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\ContentBrowser\ListView.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Resources\ContentBrowser\FolderLarge.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
		<Resource Include="Resources\ContentBrowser\FolderSmall.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\PrimitiveMeshView\CheckerMap.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
	<ItemGroup>
		<None Include="Resources\PrimitiveMeshView\PlaneTexture.png" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="envdte" Version="17.12.40391" />
	  <PackageReference Include="envdte80" Version="17.12.40391" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\PrimitiveMeshView\PlaneTexture.png">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Resource>
	</ItemGroup>
</Project>
